name: DeployWebApp_FlaskToDockerHubAndYC

on:
  push:
    branches:
      - master

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}  # Логин Docker Hub
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}       # Токен Docker Hub
  DOCKER_IMAGE_NAME: "webapp-flask"                       # Название образа
  DOCKER_IMAGE_TAG: "latest"                              # Тег образа
  YC_VM_USER: ${{ secrets.YC_VM_USER }}                   # Пользователь ВМ Yandex Cloud
  YC_VM_IP: ${{ secrets.YC_VM_IP }}                       # IP виртуальной машины
  YC_SSH_PKEY: ${{ secrets.YC_SSH_PKEY }}             # Приватный SSH-ключ для подключения
  YC_PASSPHRASE: ${{ secrets.YC_PASSPHRASE }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key with passphrase
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /tmp
            ls -a
          host: ${{ secrets.YC_VM_IP }}
          user: ${{ secrets.YC_VM_USERNAME }}
          key: ${{ secrets.KEY}}
          pass: ${{ secrets.YC_PASSPHRASE}}

      - name: Connect and run a command
        run: |
          ssh -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              irper@158.160.13.76 \
              "echo 'Hello from GitHub Actions!'"
 

