name: DeployWebApp_FlaskToDockerHubAndYC

on:
  push:
    branches:
      - master

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}  # Логин Docker Hub
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}       # Токен Docker Hub
  DOCKER_IMAGE_NAME: "webapp-flask"                       # Название образа
  DOCKER_IMAGE_TAG: "latest"                              # Тег образа
  YC_VM_USER: ${{ secrets.YC_VM_USER }}                   # Пользователь ВМ Yandex Cloud
  YC_VM_IP: ${{ secrets.YC_VM_IP }}                       # IP виртуальной машины
  YC_SSH_PKEY: ${{ secrets.YC_SSH_PKEY }}             # Приватный SSH-ключ для подключения
  YC_PASSPHRASE: ${{ secrets.YC_PASSPHRASE }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 158.160.13.76
          username: irper
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.YC_PASSPHRASE }}
          script: |
            echo "Hello from GitHub Actions!"


