name: DeployWebApp_FlaskToDockerHubAndYC

on:
  push:
    branches:
      - master

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}  # Логин Docker Hub
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}       # Токен Docker Hub
  DOCKER_IMAGE_NAME: "webapp-flask"                       # Название образа
  DOCKER_IMAGE_TAG: "latest"                              # Тег образа
  YC_VM_USER: ${{ secrets.YC_VM_USER }}                   # Пользователь ВМ Yandex Cloud
  YC_VM_IP: ${{ secrets.YC_VM_IP }}                       # IP виртуальной машины
  YC_SSH_PKEY: ${{ secrets.YC_SSH_PKEY }}             # Приватный SSH-ключ для подключения
  YC_PASSPHRASE: ${{ secrets.YC_PASSPHRASE }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Логинимся в Docker Hub и пушим образ
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .

      - name: Push Docker image
        run: docker push $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

      - name: Connect to YC VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.YC_VM_IP }}
          username: ${{ secrets.YC_VM_USER }}
          key: ${{ secrets.YC_SSH_PKEY }}
          passphrase: ${{ secrets.YC_PASSPHRASE }}
          port: 22

      - name: Deploy to Yandex Cloud VM
        run: |
          "
          docker stop $DOCKER_IMAGE_NAME || true && \
          docker rm $DOCKER_IMAGE_NAME || true && \
          docker pull $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG && \
          docker run -d --name $DOCKER_IMAGE_NAME -p 80:5000 $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
          "