name: DeployWebApp_FlaskToDockerHubAndYC

on:
  push:
    branches:
      - master

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}  # Логин Docker Hub
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}       # Токен Docker Hub
  DOCKER_IMAGE_NAME: "webapp-flask"                       # Название образа
  DOCKER_IMAGE_TAG: "latest"                              # Тег образа
  YC_VM_USER: ${{ secrets.YC_VM_USER }}                   # Пользователь ВМ Yandex Cloud
  YC_VM_IP: ${{ secrets.YC_VM_IP }}                       # IP виртуальной машины
  YC_SSH_PKEY: ${{ secrets.YC_SSH_PKEY }}             # Приватный SSH-ключ для подключения
  YC_PASSPHRASE: ${{ secrets.YC_PASSPHRASE }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sshpass and add key
        env:
          SSH_PASSPHRASE: ${{ secrets.YC_PASSPHRASE }}
        run: |
          sudo apt-get install -y sshpass
          mkdir -p ~/.ssh
          echo "${{ secrets.KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval $(ssh-agent -s)
          sshpass -p "$SSH_PASSPHRASE" ssh-add ~/.ssh/id_ed25519

      - name: Connect and run a command
        run: |
          ssh -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              irper@158.160.13.76 \
              "echo 'Hello from GitHub Actions!'"
 

      - name: Deploy to Yandex Cloud VM
        run: |
          "
          docker stop $DOCKER_IMAGE_NAME || true && \
          docker rm $DOCKER_IMAGE_NAME || true && \
          docker pull $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG && \
          docker run -d --name $DOCKER_IMAGE_NAME -p 22:5000 $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
          "